const UPLOADED_ORDER_NEW = 4
const UPLOADED_ORDER_REPROCESS_SCHEDULED = 3
const WOOCOMMERCE_ORDER_REPROCESS_SCHEDULED = 3

module.exports = {
    UPLOADED_ORDER_NEW,UPLOADED_ORDER_REPROCESS_SCHEDULED,WOOCOMMERCE_ORDER_REPROCESS_SCHEDULED
}
